apiVersion: apps/v1
kind: Deployment
metadata:
  name: g3-order
  namespace: namespace-g3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: g3-order
  template:
    metadata:
      labels:
        app: g3-order
    spec:
      containers:
        - name: g3-order
          image: carolamaral/order-ilab-g3:latest
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-order
                  key: DB_USERNAME
            - name: DB_URL_ORDER
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-order
                  key: DB_URL_ORDER
            - name: API_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-order
                  key: API_AUTH_URL
            - name: API_USER_URL
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-order
                  key: API_USER_URL
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-order
                  key: KAFKA_HOST
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-order
                  key: KAFKA_TOPIC
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret-order-g3
                  key: DB_PASSWORD
          resources:
            limits:
              memory: "4Gi"
              cpu: "1"
          ports:
            - containerPort: 8080
