apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: namespace-g3
  labels:
    app: g3-order
spec:
  type: ClusterIP
  selector:
    app: g3-order
  ports:
    - port: 8080
      targetPort: 8080
